<div class="product-model">	 
	 <div class="container">
			<ol class="breadcrumb">
		    <li><a href="index.php">首頁</a></li>
		    <li class="active">關於我們</li>
		  </ol>
      <div class="col-md-9 product-model-sec">
       <div class="jumbotron">
        <div class="container">
          
          <!-- 內容 -->
<div class="spannormal" style="width:600px">
                          <p class="MsoNormal" style="text-justify: inter-ideograph; margin: 0cm 0cm 0pt; text-indent: 24pt; text-align: justify"><span style="font-size: 10pt; font-family: 新細明體; mso-ascii-font-family: Arial; mso-hansi-font-family: Arial; mso-bidi-font-family: Arial">利優電子有限公司為</span><span style="font-size: 10pt; font-family: 新細明體; mso-ascii-font-family: Verdana; mso-hansi-font-family: Verdana; mso-bidi-font-family: Arial">聯穎科技股份有限公司</span><span style="font-size: 10pt; font-family: 新細明體; mso-ascii-font-family: Arial; mso-hansi-font-family: Arial; mso-bidi-font-family: Arial">之策略聯盟伙伴</span><span lang="EN-US" style="font-size: 10pt; font-family: Arial">, </span><span style="font-size: 10pt; font-family: 新細明體; mso-ascii-font-family: Arial; mso-hansi-font-family: Arial; mso-bidi-font-family: Arial">在海內外業界以供應及製造良好品質電腦周邊線材、轉接頭</span><span lang="EN-US" style="font-size: 10pt; font-family: Arial">, </span><span style="font-size: 10pt; font-family: 新細明體; mso-ascii-font-family: Arial; mso-hansi-font-family: Arial; mso-bidi-font-family: Arial">傳輸線</span><span style="font-size: 10pt; font-family: Arial"> <span lang="EN-US">NB</span></span><span style="font-size: 10pt; font-family: 新細明體; mso-ascii-font-family: Arial; mso-hansi-font-family: Arial; mso-bidi-font-family: Arial">外接電池</span><span lang="EN-US" style="font-size: 10pt; font-family: Arial">, LED</span><span style="font-size: 10pt; font-family: 新細明體; mso-ascii-font-family: Arial; mso-hansi-font-family: Arial; mso-bidi-font-family: Arial">燈</span><span lang="EN-US" style="font-size: 10pt; font-family: Arial">, </span><span style="font-size: 10pt; font-family: 新細明體; mso-ascii-font-family: Arial; mso-hansi-font-family: Arial; mso-bidi-font-family: Arial">模具開發及其他電腦相關產品而享有一定之名聲與信譽。</span><span lang="EN-US" style="font-size: 10pt; font-family: Arial"><o:p></o:p></span></p>
<p class="MsoNormal" style="text-justify: inter-ideograph; margin: 0cm 0cm 0pt; text-indent: 24pt; text-align: justify"><span lang="EN-US" style="font-size: 10pt; font-family: Arial"><o:p>&nbsp;</o:p></span></p>
<p class="MsoNormal" style="text-justify: inter-ideograph; margin: 0cm 0cm 0pt; text-indent: 24pt; text-align: justify"><span style="font-size: 10pt; font-family: 新細明體; mso-ascii-font-family: Arial; mso-hansi-font-family: Arial; mso-bidi-font-family: Arial">我們持續開發各式產品，種類多達</span><span lang="EN-US" style="font-size: 10pt; font-family: Arial">500</span><span style="font-size: 10pt; font-family: 新細明體; mso-ascii-font-family: Arial; mso-hansi-font-family: Arial; mso-bidi-font-family: Arial">餘種，開模經驗豐富</span><span lang="EN-US" style="font-size: 10pt; font-family: Arial">; </span><span style="font-size: 10pt; font-family: 新細明體; mso-ascii-font-family: Arial; mso-hansi-font-family: Arial; mso-bidi-font-family: Arial">為確保品質</span><span lang="EN-US" style="font-size: 10pt; font-family: Arial">, </span><span style="font-size: 10pt; font-family: 新細明體; mso-ascii-font-family: Arial; mso-hansi-font-family: Arial; mso-bidi-font-family: Arial">已符合</span><span lang="EN-US" style="font-size: 10pt; font-family: Arial">RoHS</span><span style="font-size: 10pt; font-family: 新細明體; mso-ascii-font-family: Arial; mso-hansi-font-family: Arial; mso-bidi-font-family: Arial">、</span><span lang="EN-US" style="font-size: 10pt; font-family: Arial">TUV</span><span style="font-size: 10pt; font-family: 新細明體; mso-ascii-font-family: Arial; mso-hansi-font-family: Arial; mso-bidi-font-family: Arial">、</span><span lang="EN-US" style="font-size: 10pt; font-family: Arial">ISO9001</span><span style="font-size: 10pt; font-family: 新細明體; mso-ascii-font-family: Arial; mso-hansi-font-family: Arial; mso-bidi-font-family: Arial">等品質管理認證，目標以可靠之服務品質進而滿足客戶大多數的產品需求。</span><span lang="EN-US" style="font-size: 10pt; font-family: Arial"><o:p></o:p></span></p>
<p class="MsoNormal" style="text-justify: inter-ideograph; margin: 0cm 0cm 0pt; text-indent: 24pt; text-align: justify"><span lang="EN-US" style="font-size: 10pt; font-family: Arial"><o:p>&nbsp;</o:p></span></p>
<p class="MsoNormal" style="text-justify: inter-ideograph; margin: 0cm 0cm 0pt; text-indent: 24pt; text-align: justify"><span style="font-size: 10pt; font-family: 新細明體; mso-ascii-font-family: Arial; mso-hansi-font-family: Arial; mso-bidi-font-family: Arial">我們致力於以最少的成本及最短的交期幫客戶不同的訂單合併出貨</span><span lang="EN-US" style="font-size: 10pt; font-family: Arial">, </span><span style="font-size: 10pt; font-family: 新細明體; mso-ascii-font-family: Arial; mso-hansi-font-family: Arial; mso-bidi-font-family: Arial">並送至全世界各地客戶所指定的地點。我們視所有客戶為朋友並重視每次和客戶間的交流</span><span lang="EN-US" style="font-size: 10pt; font-family: Arial">, </span><span class="style171"><span style="font-size: 10pt; font-family: 新細明體; mso-ascii-font-family: Arial; mso-hansi-font-family: Arial">珍視客戶每個意見及詢價</span></span><span class="style171"><span lang="EN-US" style="font-size: 10pt">,</span></span><span class="style171"><span style="font-size: 10pt; font-family: 新細明體; mso-ascii-font-family: Arial; mso-hansi-font-family: Arial">因為這是我們不斷</span></span><span style="font-size: 10pt; font-family: 新細明體; mso-ascii-font-family: Arial; mso-hansi-font-family: Arial; mso-bidi-font-family: Arial">不斷地進步</span><span lang="EN-US" style="font-size: 10pt; font-family: Arial">, </span><span style="font-size: 10pt; font-family: 新細明體; mso-ascii-font-family: Arial; mso-hansi-font-family: Arial; mso-bidi-font-family: Arial">創新</span><span lang="EN-US" style="font-size: 10pt; font-family: Arial">, </span><span style="font-size: 10pt; font-family: 新細明體; mso-ascii-font-family: Arial; mso-hansi-font-family: Arial; mso-bidi-font-family: Arial">及和客戶一起努力、成長以致力成為我們客戶最好的選擇及夥伴的重要力量</span><span lang="EN-US" style="font-size: 10pt; font-family: Arial">,</span><span style="font-size: 10pt; font-family: 新細明體; mso-ascii-font-family: Arial; mso-hansi-font-family: Arial; mso-bidi-font-family: Arial">。除了目前已建立的產品線</span><span lang="EN-US" style="font-size: 10pt; font-family: Arial">, </span><span style="font-size: 10pt; font-family: 新細明體; mso-ascii-font-family: Arial; mso-hansi-font-family: Arial; mso-bidi-font-family: Arial">客製產品及服務品質外</span><span lang="EN-US" style="font-size: 10pt; font-family: Arial">, </span><span style="font-size: 10pt; font-family: 新細明體; mso-ascii-font-family: Arial; mso-hansi-font-family: Arial; mso-bidi-font-family: Arial">我們也加入以下新的服務內容如下以達到最高標準的人性化服務</span><span lang="EN-US" style="font-size: 10pt; font-family: Arial"><o:p></o:p></span></p>
<p class="MsoNormal" style="text-justify: inter-ideograph; margin: 0cm 0cm 0pt; text-indent: 24pt; text-align: justify"><span lang="EN-US" style="font-size: 10pt; font-family: Arial"><o:p>&nbsp;</o:p></span></p>
<p class="MsoNormal" style="text-justify: inter-ideograph; margin: 0cm 0cm 0pt 18pt; text-indent: -18pt; text-align: justify; mso-list: l0 level1 lfo1; tab-stops: list 18.0pt"><span class="style171"><span lang="EN-US" style="font-size: 10pt; mso-fareast-font-family: Arial"><span style="mso-list: Ignore">1.<span style="font: 7pt &quot;Times New Roman&quot;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></span></span></span><span class="style171"><span style="font-size: 10pt; font-family: 新細明體; mso-ascii-font-family: Arial; mso-hansi-font-family: Arial">數百種產品線上</span></span><span class="style171"><span lang="EN-US" style="font-size: 10pt">E-Store, </span></span><span class="style171"><span style="font-size: 10pt; font-family: 新細明體; mso-ascii-font-family: Arial; mso-hansi-font-family: Arial">並以庫存方式供貨以符合客戶彈性及小量的</span></span><span class="style171"><span lang="EN-US" style="font-size: 10pt">MOQ</span></span><span class="style171"><span style="font-size: 10pt; font-family: 新細明體; mso-ascii-font-family: Arial; mso-hansi-font-family: Arial">需求</span></span><span class="style171"><span lang="EN-US" style="font-size: 10pt"><o:p></o:p></span></span></p>
<p class="MsoNormal" style="text-justify: inter-ideograph; margin: 0cm 0cm 0pt 18pt; text-indent: -18pt; text-align: justify; mso-list: l0 level1 lfo1; tab-stops: list 18.0pt"><span class="style171"><span lang="EN-US" style="font-size: 10pt; mso-fareast-font-family: Arial"><span style="mso-list: Ignore">2.<span style="font: 7pt &quot;Times New Roman&quot;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></span></span></span><span class="style171"><span style="font-size: 10pt; font-family: 新細明體; mso-ascii-font-family: Arial; mso-hansi-font-family: Arial">配合客戶產品設計包裝一起出貨</span></span><span class="style171"><span lang="EN-US" style="font-size: 10pt"><o:p></o:p></span></span></p>
<p class="MsoNormal" style="text-justify: inter-ideograph; margin: 0cm 0cm 0pt 18pt; text-indent: -18pt; text-align: justify; mso-list: l0 level1 lfo1; tab-stops: list 18.0pt"><span lang="EN-US" style="font-size: 10pt; font-family: 新細明體; mso-bidi-font-family: 新細明體"><span style="mso-list: Ignore">3.<span style="font: 7pt &quot;Times New Roman&quot;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></span></span><span lang="EN-US" style="font-size: 10pt; font-family: 新細明體">CRM</span><span style="font-size: 10pt; font-family: 新細明體">導向為客戶服務<span lang="EN-US">, </span>所有資訊將一目了然</span><span lang="EN-US" style="font-size: 10pt; font-family: 新細明體; mso-bidi-font-family: Arial"><o:p></o:p></span></p>
<p class="MsoNormal" style="text-justify: inter-ideograph; margin: 0cm 0cm 0pt 18pt; text-indent: -18pt; text-align: justify; mso-list: l0 level1 lfo1; tab-stops: list 18.0pt"><span lang="EN-US" style="font-size: 10pt; font-family: Arial; mso-fareast-font-family: Arial"><span style="mso-list: Ignore">4.<span style="font: 7pt &quot;Times New Roman&quot;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></span></span><span lang="EN-US" style="font-size: 10pt; font-family: 新細明體">Sourcing –</span><span style="font-size: 10pt; font-family: 新細明體">幫客戶搜尋最好的<span lang="EN-US"> total-solution, </span>竭力為客戶節省更多成本</span><span lang="EN-US" style="font-size: 10pt; font-family: Arial"><o:p></o:p></span></p>
<p class="MsoNormal" style="text-justify: inter-ideograph; margin: 0cm 0cm 0pt 18pt; text-indent: -18pt; text-align: justify; mso-list: l0 level1 lfo1; tab-stops: list 18.0pt"><span lang="EN-US" style="font-size: 10pt; font-family: Arial; mso-fareast-font-family: Arial"><span style="mso-list: Ignore">5.<span style="font: 7pt &quot;Times New Roman&quot;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></span></span><span lang="EN-US" style="font-size: 10pt; font-family: 新細明體">Layout</span><span style="font-size: 10pt; font-family: 新細明體">設計<span lang="EN-US">, tooling build</span>代客開發<span lang="EN-US">, </span>認證等服務</span><span lang="EN-US" style="font-size: 10pt; font-family: Arial"><o:p></o:p></span></p>
<p class="MsoNormal" style="text-justify: inter-ideograph; margin: 0cm 0cm 0pt; text-align: justify"><span class="style171"><span lang="EN-US" style="font-size: 10pt"><o:p>&nbsp;</o:p></span></span></p>
<p class="MsoNormal" style="text-justify: inter-ideograph; margin: 0cm 0cm 0pt; text-align: justify"><span class="style171"><span style="font-size: 10pt; font-family: 新細明體; mso-ascii-font-family: Arial; mso-hansi-font-family: Arial">若有任合問題或需求</span></span><span class="style171"><span lang="EN-US" style="font-size: 10pt">(</span></span><span class="style171"><span style="font-size: 10pt; font-family: 新細明體; mso-ascii-font-family: Arial; mso-hansi-font-family: Arial">歡迎</span></span><span class="style171"><span lang="EN-US" style="font-size: 10pt">OEM), </span></span><span class="style171"><span style="font-size: 10pt; font-family: 新細明體; mso-ascii-font-family: Arial; mso-hansi-font-family: Arial">請不吝與我們聯繫</span></span><span class="style171"><span lang="EN-US" style="font-size: 10pt">, </span></span><span class="style171"><span style="font-size: 10pt; font-family: 新細明體; mso-ascii-font-family: Arial; mso-hansi-font-family: Arial">並至我們網站</span></span><span lang="EN-US"><span style="font-size: 10pt; font-family: Arial">www.5ghome.com</span></span><span class="style171"><span lang="EN-US" style="font-size: 10pt"> </span></span><span class="style171"><span style="font-size: 10pt; font-family: 新細明體; mso-ascii-font-family: Arial; mso-hansi-font-family: Arial">檢視我們提供的產品線。另在首頁</span></span><span class="style171"><span lang="EN-US" style="font-size: 10pt">”what is news”</span></span><span class="style171"><span style="font-size: 10pt; font-family: 新細明體; mso-ascii-font-family: Arial; mso-hansi-font-family: Arial">裡有展示我們最新的產品</span></span><span class="style171"><span lang="EN-US" style="font-size: 10pt">, </span></span><span class="style171"><span style="font-size: 10pt; font-family: 新細明體; mso-ascii-font-family: Arial; mso-hansi-font-family: Arial">於此網站也可和我們聯絡並以郵寄方式取得最新的產品目錄。</span></span><span class="style171"><span lang="EN-US" style="font-size: 10pt"><o:p></o:p></span></span></p>
<p class="MsoNormal" style="text-justify: inter-ideograph; margin: 0cm 0cm 0pt; text-align: justify"><span class="style171"><span lang="EN-US" style="font-size: 10pt"><o:p>&nbsp;</o:p></span></span></p>
<p class="MsoNormal" style="text-justify: inter-ideograph; margin: 0cm 0cm 0pt; text-align: justify"><span class="style171"><span style="font-size: 10pt; font-family: 新細明體; mso-ascii-font-family: Arial; mso-hansi-font-family: Arial">我們期許在不久的將來可和貴司建立長久合作關係</span></span><span class="style171"><span lang="EN-US" style="font-size: 10pt">, </span></span><span class="style171"><span style="font-size: 10pt; font-family: 新細明體; mso-ascii-font-family: Arial; mso-hansi-font-family: Arial">期待您的來電及來信。</span></span><span class="style171"><span lang="EN-US" style="font-size: 10pt"><o:p></o:p></span></span></p>


          <!-- 內容 -->
                         </div>

      </div>
    </div>
      </div>
			<?php
        include("include_aboutLeftMenu.php");
      ?>
	   </div>
		</div>
</div>
<nav>
  <ul>
    <li><a href="" title=""></a></li>
  </ul>
</nav>